### ISSUE TITLE
Product Catalog API Endpoints

### ISSUE THREAD

**Issue by Sharif37** [Sharif37/MudirDokan#2]
**Description:**
Build the necessary API endpoints to manage the product catalog (food and grocery items).

**Tasks:**
- [x] Create API endpoint to add new products.
- [ ] Create an API endpoint to fetch all products with pagination.
- [ ] Create functionality for filtration based on each column of tables.  
- [x] Create API endpoint to update product details.
- [x] Create API endpoint to delete products.

**Expected Outcome:**  
A fully functional product catalog API that supports create, read, update, and delete operations.
