### ISSUE TITLE
Shopping Cart Functionality

### ISSUE THREAD

**Issue by Sharif37** [Sharif37/MudirDokan#3]
**Description:**
Implement the shopping cart feature that allows users to add and remove products before placing an order.

**Tasks:**
- [ ] Create API to add products to the shopping cart.
- [ ] Create API to remove products from the cart.
- [ ] Implement API to update product quantity in the cart.
- [ ] Create API to fetch all items in the user's cart using paginations.
- [ ] Create functionality for filtration based on each column of tables.

**Expected Outcome:**  
A working shopping cart that allows users to manage their selected products.
