### ISSUE TITLE
Order Management System

### ISSUE THREAD

**Issue by Sharif37** [Sharif37/MudirDokan#4]
**Description:**
Build the order management system, allowing users to place orders and track their status.

**Tasks:**
- [ ] Create API to place an order.
- [ ] Implement order tracking by adding order status (e.g., processing, shipped, delivered).
- [ ] Add order history retrieval for users. 
- [ ] get all order info for admins (use paginations) 
- [ ] Create functionality for filtration based on each column of tables.
- [ ] Integrate the payment gateway (e.g., Stripe) for order payment processing.

**Expected Outcome:**  
Users should be able to place orders, track their order status, and see their order history.
